### ISSUE TITLE
ESP not drawing correctly

### ISSUE THREAD

**Issue by ElectfriedTheGod** [GuilhermeRaposo/CSGO_ExternalTrainer#1]
The ESP boxes and lines only show briefly when tabbing in and out of the game, but halos / chams work as intended? tested on both windows 7 and windows 10, and updated to the latest offsets.

**Comment by GuilhermeRaposo** [comment]
Make sure the display settings on CSGO is set to windowed mode.

The way the ESP works is by drawing lines/text on top of the game window, so if you’re playing on fullscreen mode you won’t see anything being draw because the game window is taking the whole screen.

**Comment by ElectfriedTheGod** [comment]
![csgo_Sb6mqbvkUg](https://user-images.githubusercontent.com/37424196/80400630-af82d580-8880-11ea-848e-f687cfd313ca.png)
Draws in the corner of my screen :x
however glow halos work fine, thank you for quicky response
